<?php
/**
 * HTMLに埋め込むタイトルを定義する
 */
return [
    //===========================================
    // TOP
    //===========================================
    'top'                      => 'https://zeus-wifi.jp/',
    'charm'                    => 'https://zeus-wifi.jp/charm',
    'price'                    => 'https://zeus-wifi.jp/price',
    'guide'                    => 'https://zeus-wifi.jp/guide',
    'overseas'                 => 'https://zeus-wifi.jp/overseas',
    'overseas_use'             => 'https://zeus-wifi.jp/overseas_use',
    'cloudwifi'                => '', // Deleted page
    'device_insurance'         => '', // Deleted page
    'unlimited_data'           => '', // Deleted page
    'zeus_wifi_debut'          => '', // Deleted page
    'anshin_kaiyaku'           => 'https://zeus-wifi.jp/anshin_kaiyaku',
    'cm'                       => 'https://zeus-wifi.jp/cm',
    'news'                     => 'https://zeus-wifi.jp/news',
    'news_20200330'            => 'https://zeus-wifi.jp/news/20200330',
    'callcenter'               => 'https://zeus-wifi.jp/support/callcenter',
    'taikencampaign'           => 'https://zeus-wifi.jp/taikencampaign',
    'campaign_archive'         => 'https://zeus-wifi.jp/campaign_archive',
    'column'                   => 'https://zeus-wifi.jp/column',
    'column_2'                 => 'https://zeus-wifi.jp/column_2',
    'column_detail_1'          => 'https://zeus-wifi.jp/column_detail_1',
    'column_detail_2'          => 'https://zeus-wifi.jp/column_detail_2',
    'column_detail_3'          => 'https://zeus-wifi.jp/column_detail_3',
    'column_detail_4'          => 'https://zeus-wifi.jp/column_detail_4',
    'column_detail_5'          => 'https://zeus-wifi.jp/column_detail_5',
    'column_detail_6'          => 'https://zeus-wifi.jp/column_detail_6',
    'column_detail_7'          => 'https://zeus-wifi.jp/column_detail_7',
    'terms'                    => 'https://zeus-wifi.jp/terms',
    'company'                  => 'https://zeus-wifi.jp/company',
    'business'                 => 'https://zeus-wifi.jp/business',
    'business_partner'         => 'https://zeus-wifi.jp/business_partner',
    'business_special'         => 'https://zeus-wifi.jp/business_special',
    'hotel_plan'               => 'https://zeus-wifi.jp/hotel_plan',
    'dual'                     => 'https://zeus-wifi.jp/dual',
    'promotion_dual'           => 'https://zeus-wifi.jp/promotion_dual',
    'instruction_manual_language' => 'https://zeus-wifi.jp/instruction_manual_language',
    'hotel_wifi_movie_01'      => 'https://zeus-wifi.jp/hotel_wifi_movie_01',
    'hotel_wifi_movie_02'      => 'https://zeus-wifi.jp/hotel_wifi_movie_02',
    'promotion_newservice'     => 'https://zeus-wifi.jp/promotion_newservice',
    'promotion_newservice_lp01'=> 'https://zeus-wifi.jp/promotion_newservice_lp01',
    'promotion_newservice_lp02'=> 'https://zeus-wifi.jp/promotion_newservice_lp02',
    'promotion_newservice_lp03'=> 'https://zeus-wifi.jp/promotion_newservice_lp03',
    'promotion_newservice_lp04'=> 'https://zeus-wifi.jp/promotion_newservice_lp04',
    'promotion_newservice_lp05'=> 'https://zeus-wifi.jp/promotion_newservice_lp05',
    'promotion_newservice_lp06'=> 'https://zeus-wifi.jp/promotion_newservice_lp06',
    'promotion_newservice_lp07'=> 'https://zeus-wifi.jp/promotion_newservice_lp07',
    'limitedplan_term'         => 'https://zeus-wifi.jp/limitedplan/specialcampaignterms',
    'faq'                      => 'https://zeus-wifi.jp/faq',
    'planselect'               => 'https://zeus-wifi.jp/planselect',
    'contract_initial_cancel'  => 'https://zeus-wifi.jp/contract_initial_cancel',
    'setcampaign_new'          => 'https://zeus-wifi.jp/setcampaign_new',
    'setcampaign_existing'     => 'https://zeus-wifi.jp/setcampaign_existing',
    'setcampaign_existing_terms'  => 'https://zeus-wifi.jp/setcampaign_existing_terms',
    'setcampaign_new_terms'    => 'https://zeus-wifi.jp/setcampaign_new_terms',
    'twittercampaign_terms'    => 'https://zeus-wifi.jp/twittercampaign_terms',
    'twitter_terms'            => 'https://zeus-wifi.jp/twitter_terms',
    'contact'                  => 'https://zeus-wifi.jp/support_contact',

    'login'                    => 'https://zeus-wifi.jp/login',
    'wimaxlogin'               => 'https://zeus-wifi.jp/entry/wimax/login',

    'castingroad'              => 'https://zeus-wifi.jp/castingroad',
    'wimax'                    => 'https://zeus-wifi.jp/wimax',
    'wimax_zeus_set'           => 'https://zeus-wifi.jp/wimax/zeus_set',
    'wimax_terms'              => 'https://zeus-wifi.jp/wimax_terms',
    'wimax_contact'            => 'https://zeus-wifi.jp/wimax_support_contact',
    'wimax_contact_confirm'    => 'https://zeus-wifi.jp/wimax_support_contact/confirm',
    'wimax_contact_complete'   => 'https://zeus-wifi.jp/wimax_support_contact/complete',
    'wimax_device_faq'         => 'https://zeus-wifi.jp/wimax_device_faq',
    'wimax_trouble_shooting'   => 'https://zeus-wifi.jp/wimax_trouble_shooting',
    'wimax_news'               => 'https://zeus-wifi.jp/wimax_news',
    'openhouse'                => 'https://zeus-wifi.jp/openhouse',
    'company_openhouse'        => 'https://zeus-wifi.jp/company_openhouse',
    'promotion_chiba_lotte'    => 'https://zeus-wifi.jp/clm_campaign',
    'promotion_kagoshima_rebnise' => 'https://zeus-wifi.jp/kgr_specialplans',
    'wimax_limited'            => 'https://zeus-wifi.jp/wimax_limited',
    'wimax_campaign'           => 'https://zeus-wifi.jp/wimax_campaign',
    'insurance_option'         => 'https://zeus-wifi.jp/insurance_option',
    'saison_campaign'          => 'https://zeus-wifi.jp/saison_campaign',
    'bulk_prepayment'          => 'https://zeus-wifi.jp/bulk_prepayment',
    'global_contact'            => 'https://zeus-wifi.jp/global_support_contact',
    'global_contact_confirm'    => 'https://zeus-wifi.jp/global_support_contact/confirm',
    'global_contact_complete'   => 'https://zeus-wifi.jp/global_support_contact/complete',
    'prepaid_contact'            => 'https://zeus-wifi.jp/prepaid_support_contact',
    'prepaid_contact_confirm'    => 'https://zeus-wifi.jp/prepaid_support_contact/confirm',
    'prepaid_contact_complete'   => 'https://zeus-wifi.jp/prepaid_support_contact/complete',
];
