<?php
/**
 * HTMLに埋め込むCSSを定義する
 */
return [
    //===========================================
    // TOP
    //===========================================
    'top'                      => ['common.css','top.css','top-tb.css','style.css','buttons.css','news.css','subsc-tb.css','subsc-top-tb.css'],
    'charm'                    => ['common.css','style.css','subsc-tb.css','subsc-charm-tb.css'],
    'price'                    => ['common.css','top.css','top-tb.css','style.css','news.css','subsc-tb.css','subsc-price-tb.css'],
    'device'                   => ['common.css','style.css','parts.css','subsc-tb.css','subsc-device-tb.css'],
    'guide'                    => ['common.css','style.css','subsc-tb.css','subsc-guide-tb.css'],
    'faq'                      => ['common.css','style.css','parts.css','contact.css','news.css','subsc-tb.css','subsc-faq-tb.css'],
    'overseas'                 => ['common.css','style.css','parts.css','overseas.css'],
    'overseas_use'             => ['common.css','style.css','parts.css','overseas.css','subsc-tb.css','subsc-overseas_use-tb.css'],
    'anshin_kaiyaku'           => ['common.css','style.css','subsc-tb.css','subsc-anshin_kaiyaku-tb.css'],
    'cm'                       => ['common.css','style.css'],
    'news'                     => ['common.css','style.css','news.css','subsc-tb.css','subsc-news-tb.css'],
    // 'news_20220708'            => ['common.css','style.css','news.css'],
    // 'news_20200330'            => ['common.css','style.css'],
    'callcenter'               => ['common.css','style.css','news.css','subsc-tb.css','subsc-callcenter_contact-tb.css'],
    // 'taikencampaign'           => ['common.css','style.css'],
    'campaign_archive'         => ['common.css','style.css','news.css','subsc-tb.css','subsc-campaign_archive-tb.css'],
    'dual'                     => ['common.css','top.css','style.css','parts.css','subsc-tb.css','subsc-dual-tb.css'],
    'instruction_manual_language' => ['common.css','style.css','subsc-tb.css','subsc-hotel_wifi-tb.css'],
    'column'                   => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'column_2'                 => ['common.css','style.css','contact.css'],
    'column_detail_1'          => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'column_detail_2'          => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'column_detail_3'          => ['common.css','style.css','contact.css'],
    'column_detail_4'          => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'column_detail_5'          => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'column_detail_6'          => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'column_detail_7'          => ['common.css','style.css','contact.css','subsc-tb.css','subsc-column-tb.css'],
    'terms'                    => ['common.css','style.css','subsc-tb.css','subsc-terms-tb.css'],
    'company'                  => ['common.css','style.css','subsc-tb.css'],
    'business'                 => ['common.css','top.css','parts.css','style.css','news.css','business.css','subsc-biz-tb.css', 'top-tb.css'],
    'business_partner'         => ['common.css','style.css','parts.css','contact.css','news.css','business_partner.css','subsc-tb.css','subsc-biz-partner-tb.css'],
    'business_special'         => ['common.css','style.css','subsc-tb.css','subsc-hotel_wifi-tb.css','business_special.css'],
    'hotel_plan'               => ['common.css','top.css','style.css','news.css','subsc-tb.css','subsc-biz-partner-tb.css'],
    'contract_initial_cancel'  => ['common.css','style.css','subsc-tb.css','subsc-contract_initial_cancel-tb.css'],
    'contact'                  => ['common.css','style.css','entry.css','contact.css','news.css','subsc-tb.css','subsc-callcenter_contact-tb.css'],
    'contact_confirm'          => ['common.css','style.css','entry.css','contact.css','subsc-tb.css','subsc-callcenter_contact-tb.css'],
    'contact_complete'         => ['common.css','style.css','entry.css','contact.css','subsc-tb.css','subsc-callcenter_contact-tb.css'],
    'castingroad'              => ['common.css','top.css'],
    'wimax'                    => ['common.css','parts.css','wimax.css','wimax_campaign.css'],
    'wimax_campaign'           => ['common.css','parts.css','wimax.css'],
    'wimax_terms'              => ['common.css','style.css','wimax.css'],
    'wimax_limited'            => ['common.css','parts.css','wimax_limited.css','wimax.css','news.css'],
    'wimax_zeus_set'           => ['common.css','parts.css','wimax_zeus_set.css'],
    'openhouse'                => ['lp_ouchilink.css','buttons.css','subsc-ouchilink-tb.css'],
    'company_openhouse'        => ['lp_ouchilink.css','subsc-ouchilink-tb.css'],
    'wimax_contact'            => ['common.css','style.css','contact.css','wimax.css','entry.css','wimax-tb.css'],
    'wimax_contact_confirm'    => ['common.css','style.css','contact.css','wimax.css','entry.css','wimax-tb.css'],
    'wimax_contact_complete'   => ['common.css','style.css','contact.css','wimax.css','entry.css','wimax-tb.css'],
    'wimax_device_faq'         => ['common.css','parts.css','wimax.css'],
    'wimax_trouble_shooting'   => ['common.css','parts.css','wimax.css'],
    'wimax_news'               => ['common.css','style.css','wimax.css'],
    'wimax_news_20220708'      => ['common.css','style.css','wimax.css'],
    'insurance_option'         => ['common.css','top.css','style.css','news.css','subsc-tb.css','subsc-insurance_option-tb.css'],
    'saison_campaign'          => ['common.css','top.css','style.css','news.css','subsc-tb.css','subsc-insurance_option-tb.css','saison_campaign.css'],
    'login'                    => ['common.css','style.css','mypage.css','mypage-button.css','login.css','mypage_tb.css'],
    'repeat_login'             => ['common.css','style.css','mypage.css','mypage-button.css','login.css','mypage-overseas.css','entry.css','mypage_tb.css'],
    'forget_password'          => ['common.css','style.css','mypage.css','mypage-button.css','login.css','mypage_tb.css'],
    'forget_password_complete' => ['common.css','style.css','mypage.css','mypage-button.css','login.css','mypage_tb.css'],
    'global_contact'            => ['common.css','style.css','contact.css','global_contact.css','entry.css','global_contact_tb.css'],
    'global_contact_confirm'    => ['common.css','style.css','contact.css','global_contact.css','entry.css','global_contact_tb.css'],
    'global_contact_complete'   => ['common.css','style.css','contact.css','global_contact.css','entry.css','global_contact_tb.css'],
    'prepaid_contact'            => ['common.css','style.css','contact.css','prepaid_contact.css','entry.css','prepaid_contact_tb.css'],
    'prepaid_contact_confirm'    => ['common.css','style.css','contact.css','prepaid_contact.css','entry.css','prepaid_contact_tb.css'],
    'prepaid_contact_complete'   => ['common.css','style.css','contact.css','prepaid_contact.css','entry.css','prepaid_contact_tb.css'],
    'twitter_terms'             => ['common.css','style.css','subsc-tb.css','subsc-hotel_wifi-tb.css','twitter_terms.css'],
];
